### ISSUE TITLE
task: (backlog) sdr-preservation-core code  -- is there any logic to be abstracted out?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation2017#36]
Is this code base merely what is needed for the robots to execute, with the meaty logic used by the robots abstracted out?

**Comment by LynnMcRae** [comment]
You know my old refrain on this. The ideal robot is one that wakes up, makes a service call, and records the answer. Where we were once headed (quite a while ago) is that a workflow step could be a defined by a service URI in its definition, rather than a robot, so that this basic pattern would be built into the framework. We obviously never got there, and robots tend to do more than one thing these days. 

But the idea that services can be used by robots or called independently is important, so we don't have things that can only be done by engaging a robot outside the context of its workflow.

**Comment by ndushay** [comment]
closed in favor of sul-dlss/sdr-preservation-core/issues/75
